#!/usr/bin/env ruby

ARGV.empty? and abort("no files given")

ARGV.each do |filename|

  chunks = []
  File.open(filename, "rb") do |file|

    1024.times do |i|
      offset, sectors = file.read(4).unpack("L>XC")
      offset >>= 8
      chunks.push({ offset: offset, sectors: sectors })
    end

    1024.times do |i|
      timestamp = Time.at(file.read(4).unpack("L>").first)
      chunks[i].merge!({ timestamp: timestamp })
    end

    
    chunks.sort_by { |c| c[:timestamp] }.reverse.each do |c|
      p c
    end

  end

end

